on:
  push:

env:
  CMAKE_VERSION: 3.27.4

jobs:
  # test the build
  build:
    runs-on: ubuntu-latest
    steps:
    - name: deps
      run: sudo apt-get update && sudo apt-get install -qqy build-essential libabsl-dev libboost-all-dev libgrpc++-dev libprotobuf-dev libxtensor-dev pkg-config ninja-build protobuf-compiler-grpc git wget
    - name: latest cmake
      run: |
        cd ~
        wget https://github.com/Kitware/CMake/releases/download/v${CMAKE_VERSION}/cmake-${CMAKE_VERSION}-linux-x86_64.sh
        chmod +x cmake-${CMAKE_VERSION}-linux-x86_64.sh
        cd /usr
        sudo ~/cmake-${CMAKE_VERSION}-linux-x86_64.sh --skip-license
    - uses: actions/checkout@v3
    - name: cmake
      run: |
        cmake --version
        mkdir build && cd build && cmake .. -G Ninja
        ninja module-example-cpp
    - name: inspect output
      run: |
        file module-example-cpp
        ldd module-example-cpp
