on:
  push:
  release:
    types: [published]

env:
  CMAKE_VERSION: 3.27.4
  VERSION: ${{ github.event_name == 'release' && github.ref_name || format('0.0.0-{0}.{1}', github.ref_name, github.run_number) }}

jobs:
  build:
    strategy:
      matrix:
        include:
        - runs-on: buildjet-4vcpu-ubuntu-2204
          arch: amd64
        - runs-on: buildjet-4vcpu-ubuntu-2204-arm
          arch: arm64
    runs-on: ${{ matrix.runs-on }}
    container: debian:bullseye
    steps:
    - uses: actions/checkout@v3
    - name: deps
      run: apt-get update && ./apt-setup.sh
    - name: latest cmake
      run: |
        cd ~
        ARCH=$(uname -m)
        wget --quiet https://github.com/Kitware/CMake/releases/download/v${CMAKE_VERSION}/cmake-${CMAKE_VERSION}-linux-$ARCH.sh
        chmod +x cmake-${CMAKE_VERSION}-linux-$ARCH.sh
        cd /usr
        ~/cmake-${CMAKE_VERSION}-linux-$ARCH.sh --skip-license
    - name: build
      run: make module.tar.gz
    - name: inspect output
      run: |
        file build/module-example-cpp
        du -hc build/module-example-cpp
        ldd build/module-example-cpp
        du -hc module.tar.gz
        tar tf module.tar.gz
    - uses: actions/upload-artifact@v3
      with:
        name: bundle-${{ matrix.arch }}-${{ github.sha }}
        path: module.tar.gz
    - uses: viamrobotics/upload-module@v1
      if: github.event_name == 'release'
      with:
        module-path: module.tar.gz
        platform: linux/${{ matrix.arch }}
        version: ${{ env.VERSION }}
        key-id: ${{ secrets.viam_key_id }}
        key-value: ${{ secrets.viam_key_value }}
