on:
  push:

env:
  CMAKE_VERSION: 3.27.4
  VERSION: ${{ github.event_name == 'release' && github.ref_name || format('0.0.0-{0}.{1}', github.ref_name, github.run_number) }}

jobs:
  build:
    strategy:
      matrix:
        include:
        - runs-on: buildjet-4vcpu-ubuntu-2204
          arch: amd64
        - runs-on: buildjet-4vcpu-ubuntu-2204-arm
          arch: arm64
    runs-on: ${{ matrix.runs-on }}
    container: debian:bookworm
    steps:
    - uses: actions/checkout@v3
    - name: deps
      run: |
        apt-get update
        apt-get install -qy build-essential pkg-config ninja-build git wget libboost-log-dev file
    - name: latest cmake
      run: |
        ARCH=$(uname -m)
        wget --quiet https://github.com/Kitware/CMake/releases/download/v${CMAKE_VERSION}/cmake-${CMAKE_VERSION}-linux-$ARCH.sh
        chmod +x cmake-${CMAKE_VERSION}-linux-$ARCH.sh
        ./cmake-${CMAKE_VERSION}-linux-$ARCH.sh --skip-license --prefix=/usr
    - name: install viam sdk
      run: |
        wget https://storage.googleapis.com/packages.viam.com/debian/cpp-sdk/viam-cpp-sdk-0.0.0-bookworm-`uname -m`.deb
        apt-get install -qy ./viam-cpp-sdk-0.0.0-bookworm-`uname -m`.deb
    - name: mkdir
      run: mkdir build
    - name: build
      working-directory: build
      run: |
        cmake --version
        cmake .. -G Ninja
        ninja module-example-cpp
        file module-example-cpp
        ldd module-example-cpp
    - uses: actions/upload-artifact@v3
      with:
        name: binary-${{ matrix.arch }}
        path: build/module-example-cpp
